name: Automotive run codestyle check

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - name: poetry run all tests
        run: poetry run pytest --cov
